TimeSeries - fix confidence parameter type for some detectors (#4058)
dotnet/machinelearning pull request #5623
Opened 2021-02-15 12:03 UTC by esso23

Fixes https://github.com/dotnet/machinelearning/issues/4058

- The public API exposed confidence parameters as int even though it's internally implemented as double
- There was no workaround since all classes where double is used are internal
- This caused major issues for software requiring high precision predictions
- This change to API should be backwards compatible since int can be passed to parameter of type double

2021-02-15 12:03 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/machinelearning?pullRequest=5623) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/machinelearning?pullRequest=5623) before we can accept your contribution.<br/><br/>:x: esso23 [sign now](https://cla.dotnetfoundation.org/dotnet/machinelearning?pullRequest=5623)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/machinelearning?pullRequest=5623) it.</sub>

2021-02-17 21:49 UTC, michaelgsharp commented
hey @esso23, thanks for your pr! Let me talk with my team about this change. While it is a public API change, C# converts int to double implicitly, so I dont think it will break anything.

2021-02-17 22:06 UTC, michaelgsharp requested changes
Alright @esso23, the correct way to fix this is to overload these methods so that we still have the original int ones as well. Just doing it like this is a binary breaking change. Can you change this to overload the original methods instead? You can also mark the int ones as deprecated if you would like. If not, when your change goes in I can make another PR and mark them that way.

2021-02-17 22:31 UTC, esso23 commented
@michaelgsharp Sure, I'll look into it.

2021-02-18 17:44 UTC, michaelgsharp approved these changes
Alright, it looks good to me. Is this enough to make it so you don't need to use a modified version of ML.NET?

Our next release is targeted for the 2nd of March. So this will go in that release.

2021-02-18 17:44 UTC, merged

2021-02-18 18:56 UTC, esso23 commented
Yes, this is exactly what we needed.
Thanks