Fix incorrect DataFrame min max computation with NULL
dotnet/machinelearning pull request #6734
Opened 2023-06-14 21:04 UTC by asmirnov82

Fixes #6733

2023-06-23 18:16 UTC, JakeRadMSFT commented
Thanks @asmirnov82! Can you merge this into https://github.com/JakeRadMSFT/machinelearning/tree/u/jakerad/generic-math as well?

2023-06-23 18:19 UTC, JakeRadMSFT commented on src/Microsoft.Data.Analysis/DateTimeComputation.cs
> +                    if (((bitmapSpan[byteIndex] >> (i & 7)) & 1) == 0)
There is an internal or private function that basically does just this.

2023-06-23 18:23 UTC, JakeRadMSFT commented on src/Microsoft.Data.Analysis/DateTimeComputation.cs
> +                    if (((bitmapSpan[byteIndex] >> (i & 7)) & 1) == 0)
Hmm not finding the one I thought existed ... one second

2023-06-23 18:24 UTC, JakeRadMSFT commented on src/Microsoft.Data.Analysis/DateTimeComputation.cs
> +                    if (((bitmapSpan[byteIndex] >> (i & 7)) & 1) == 0)
https://github.com/dotnet/machinelearning/pull/6661/files#diff-bdbb32ff7a16375aa92518a41c65d77328cea77a932df1d313c77911b83b5bbcR284

2023-06-23 18:33 UTC, JakeRadMSFT requested changes
I'd like the null check to stay consistent everywhere. We can analyze perf later ... and see if in-lining would help.

2023-07-06 11:35 UTC, asmirnov82 commented
> 

This wasn't fixed by the latest changes in generic-math branch. I merged my changes, however this requires additional work to change new generic implementation (CalculateReduction method), until changes are done 2 new unit tests fail (TestIntComputations_MaxMin_WithNulls and  TestIntComputations_MaxMin_OnEmptyColumn)

2023-07-06 19:13 UTC, JakeRadMSFT commented
> > Thanks @asmirnov82! Can you merge this into https://github.com/JakeRadMSFT/machinelearning/tree/u/jakerad/generic-math as well?
> > It's possible this was fixed by other changes in the generic math branch. Can you make sure it meets your needs/add/update tests?
> 
> This wasn't fixed by the latest changes in generic-math branch. I merged my changes, however this requires additional work to change new generic implementation (CalculateReduction method), until changes are done 2 new unit tests fail (TestIntComputations_MaxMin_WithNulls and TestIntComputations_MaxMin_OnEmptyColumn)

Awesome @asmirnov82  - I've made those changes and merged. Can you take a look at them when you have a chance?

If you're up for it -  I'd love for you to review my generic math PR once I have the .NET 8 branch setup. 

It should be ready for review after next week.

2023-07-06 19:14 UTC, JakeRadMSFT commented
Merged into Generic Math branch!

2023-07-06 19:27 UTC, JakeRadMSFT approved these changes

2023-07-06 19:27 UTC, JakeRadMSFT approved these changes

2023-07-07 09:45 UTC, JakeRadMSFT commented
/azp run

2023-07-07 22:22 UTC, merged